# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Pythonhello.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1393, 768)
        MainWindow.setStyleSheet("")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setEnabled(True)
        self.centralwidget.setAutoFillBackground(False)
        self.centralwidget.setStyleSheet("\n"
"QMainWindow#QWidget{background-image: url(:/picture/1.png)\n"
"\n"
"}")
        self.centralwidget.setObjectName("centralwidget")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(30, 20, 1341, 701))
        self.widget.setStyleSheet("border-image: url(:/picture/监控界面_00.png);")
        self.widget.setObjectName("widget")
        self.openGLWidget = QtWidgets.QOpenGLWidget(self.widget)
        self.openGLWidget.setGeometry(QtCore.QRect(469, 169, 261, 191))
        self.openGLWidget.setObjectName("openGLWidget")
        self.openGLWidget_2 = QtWidgets.QOpenGLWidget(self.widget)
        self.openGLWidget_2.setGeometry(QtCore.QRect(740, 170, 251, 191))
        self.openGLWidget_2.setObjectName("openGLWidget_2")
        self.openGLWidget_3 = QtWidgets.QOpenGLWidget(self.widget)
        self.openGLWidget_3.setGeometry(QtCore.QRect(1000, 170, 251, 191))
        self.openGLWidget_3.setObjectName("openGLWidget_3")
        self.openGLWidget_4 = QtWidgets.QOpenGLWidget(self.widget)
        self.openGLWidget_4.setGeometry(QtCore.QRect(470, 380, 261, 201))
        self.openGLWidget_4.setObjectName("openGLWidget_4")
        self.openGLWidget_5 = QtWidgets.QOpenGLWidget(self.widget)
        self.openGLWidget_5.setGeometry(QtCore.QRect(740, 380, 251, 201))
        self.openGLWidget_5.setObjectName("openGLWidget_5")
        self.openGLWidget_6 = QtWidgets.QOpenGLWidget(self.widget)
        self.openGLWidget_6.setGeometry(QtCore.QRect(1000, 380, 251, 201))
        self.openGLWidget_6.setObjectName("openGLWidget_6")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1393, 24))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
import picture_rc
